Update docs
irisnet/irishub pull request #2469
Opened 2020-12-09 08:05 UTC by dgsbl

2020-12-09 08:11 UTC, zhiqiang-bianjie commented on docs/cli-client/wasm.md
> +Wasm module allows you to manage wasm
Wasm module allows you to manage smart contract

2020-12-09 08:15 UTC, zhiqiang-bianjie commented on docs/cli-client/wasm.md
> +## iris tx wasm execute
command should be order by `store`、`instantiate `、`execute `、`migrate `、

2020-12-09 08:16 UTC, chengwenxi requested changes

2020-12-09 08:16 UTC, chengwenxi commented on docs/zh/cli-client/gov.md
> +| [proposer](#iris-query-gov-proposer)            | 查询使用给定ID提出建议的地址                                    |
查询给定ID提议的提议者

2020-12-09 08:16 UTC, chengwenxi commented on docs/zh/cli-client/gov.md
> +查询使用给定ID提出建议的地址。
ditto

2020-12-09 08:18 UTC, zhiqiang-bianjie commented on docs/zh/cli-client/gov.md
> +| [proposer](#iris-query-gov-proposer)            | 查询使用给定ID提出建议的地址                                    |
通过提议ID查询提案的发起人地址

2020-12-09 09:14 UTC, chengwenxi approved these changes

2020-12-10 03:33 UTC, zhiqiang-bianjie approved these changes

2020-12-10 05:36 UTC, merged