Rest migrate
irisnet/irishub pull request #2474
Opened 2020-12-23 06:33 UTC by dgsbl

2020-12-23 08:51 UTC, chengwenxi requested changes

2020-12-23 08:51 UTC, chengwenxi commented on modules/legacy/client/rest/rpc/block.go
> +		NumTxs:             0,
```suggestion
		NumTxs:             int64(len(tmBlock.Block.Data.Txs)),
```

2020-12-23 08:51 UTC, chengwenxi commented on modules/legacy/client/rest/tx/query.go
> +//}
delete unused code

2020-12-24 01:58 UTC, chengwenxi approved these changes

2020-12-24 02:37 UTC, zhiqiang-bianjie approved these changes

2020-12-24 02:40 UTC, merged