Update cosmos-sdk version
irisnet/irishub pull request #2478
Opened 2020-12-29 10:09 UTC by dgsbl

2020-12-29 10:52 UTC, chengwenxi requested changes
Please update swagger generation script

2020-12-29 10:52 UTC, chengwenxi commented on CHANGELOG.md
> -  * [\#1432](https://github.com/irisnet/irishub/issues/1432) [crypto] Allow PubKeyMultisigThreshold to unmarshal into crypto.PubKey
revert changelog

2020-12-30 06:31 UTC, chengwenxi approved these changes

2020-12-30 06:40 UTC, zhiqiang-bianjie approved these changes

2020-12-30 06:42 UTC, merged