docs cli-client update
irisnet/irishub pull request #2494
Opened 2021-01-13 10:06 UTC by seekelvis

2021-01-13 10:17 UTC, chengwenxi requested changes
fix typo

2021-01-13 10:17 UTC, chengwenxi commented on docs/cli-client/gov.md
> +IMPORTANT: Currently parameter changes are evaluated but not validated, so it is very  important that any "value" change is valid (ie. correct type and within bounds) for its respective parameter, eg
`very  important` -> `very important`

2021-01-13 11:08 UTC, chengwenxi approved these changes

2021-01-15 08:40 UTC, dreamer-zq approved these changes

2021-01-15 08:41 UTC, merged