Update nft features doc
irisnet/irishub pull request #2507
Opened 2021-01-19 09:14 UTC by dgsbl

2021-01-20 05:49 UTC, SegueII approved these changes

2021-01-20 06:11 UTC, chengwenxi requested changes
No need to specify global params in this doc.

2021-01-20 06:11 UTC, chengwenxi commented on docs/features/nft.md
> +-_Denom_: the globally unique asset class name
```suggestion
-_Denom_: the globally unique nft category name
```

2021-01-20 06:11 UTC, chengwenxi commented on docs/features/nft.md
> +-_Denom ID_: the globally unique asset class identifier of Denom
```suggestion
-_Denom ID_: the globally unique nft category identifier of Denom
```

2021-01-20 06:11 UTC, chengwenxi commented on docs/features/nft.md
> +Specify the nft Denom (nft category), metadata JSON Schema, sender, chain ID and fee to issue nft.
issue nft need additional fee? If it's the tx fees, delete it.

2021-01-20 06:11 UTC, chengwenxi commented on docs/features/nft.md
> +Specify the nft Denom (nft category), metadata JSON Schema, sender, chain ID and fee to issue nft.
delete chain-id

2021-01-20 06:11 UTC, chengwenxi commented on go.mod
> +	github.com/irisnet/irismod v1.2.1-0.20210119082202-5a59684d2b78
update irismod version via another PR

2021-02-07 08:13 UTC, chengwenxi approved these changes

2021-02-07 08:17 UTC, merged