Update get-started doc
irisnet/irishub pull request #2509
Opened 2021-01-19 10:31 UTC by SegueII

2021-01-19 10:52 UTC, chengwenxi requested changes

2021-01-19 10:52 UTC, chengwenxi commented on docs/get-started/install.md
> +The Latest IRIShub version for Mainnet is [v1.0.0](https://github.com/irisnet/irishub/releases/v1.0.0)
v1.0.0 -> v1.0.0-rc0

2021-02-05 06:43 UTC, chengwenxi commented on docs/get-started/install.md
> +The Latest IRIShub version for Mainnet is [v1.0.0](https://github.com/irisnet/irishub/releases/v1.0.0)
no need modify it now

2021-02-07 08:40 UTC, dreamer-zq approved these changes

2021-02-25 05:39 UTC, chengwenxi approved these changes

2021-02-25 07:03 UTC, zhangyelong approved these changes

2021-02-25 07:06 UTC, merged