Wangdi/gov params
irisnet/irishub pull request #2537
Opened 2021-01-28 07:19 UTC by dgsbl

2021-02-02 10:39 UTC, chengwenxi reviewed
Could you rearrange the order of modules?

2021-02-02 10:39 UTC, chengwenxi commented on docs/concepts/gov-params.md
> +## Parameters in ibc
```suggestion
## Parameters in IBC
```

2021-02-03 09:02 UTC, haifengxi requested changes

2021-02-03 09:02 UTC, haifengxi commented on docs/concepts/gov-params.md
> +| `service/BaseDenom`            | Tokens supported by service fees                            |                           | uiris    |
BaseDenom: Token denom that must be used for deposits

2021-02-03 09:10 UTC, secret2830 commented on docs/zh/concepts/gov-params.md
> +| `auth/SigVerifyCostED25519`   | 在EDD2519算法签名验证上花费的gas     | (0, 18446744073709551615] | 590     |
交易的memo字段的最大字符数

2021-02-07 08:01 UTC, chengwenxi requested changes
Please check zh params also

2021-02-07 08:14 UTC, chengwenxi approved these changes

2021-02-07 09:26 UTC, SegueII approved these changes

2021-02-07 10:11 UTC, dreamer-zq approved these changes

2021-02-07 10:26 UTC, haifengxi approved these changes

2021-02-07 10:32 UTC, merged