Add HTLT
irisnet/irishub pull request #2592
Opened 2021-03-16 11:27 UTC by SegueII

2021-03-21 03:03 UTC, chengwenxi commented on migrate/service/migrate.go
> +	}
migrate params, see https://github.com/irisnet/irishub/issues/2589

2021-03-23 02:08 UTC, chengwenxi requested changes

2021-03-23 02:08 UTC, chengwenxi commented on app/app.go
> +		"v1", &store.StoreUpgrades{},
v1.1

2021-03-23 02:43 UTC, chengwenxi approved these changes

2021-03-23 03:00 UTC, dreamer-zq approved these changes

2021-03-23 03:00 UTC, merged